apiVersion: integration/v1
kind: Step
name: create-annotation
version: 1
summary: Post an annotation to a Grafana dashboard

description: |
  Annotate a Grafana dashboard with an event.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/grafana-step-create-annotation

examples:
- summary: Post an annotation with a given message
  content:
    apiVersion: v1
    kind: Workflow
    parameters:
      text:
        description: The annotation message
        default: Production deployment
      dashboardId:
        description: The numeric identifier of the dashboard to update
      panelId:
        description: The numeric identifier of the panel to annotate
    steps:
    - name: annotate-dashboard
      image: relaysh/grafana-step-create-annotation
      spec:
        connection: ${connections.grafana.my-grafana-connection}
        text: ${parameters.text}
        dashboardId: ${parameters.dashboardId}
        panelId: ${parameters.panelId}
        tags: [deploy, prod]

schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json
