# Step metadata - full description at:
# https://github.com/puppetlabs/relay-rfcs/blob/master/content/0006-integration-layout/rfc.md#common-metadata
apiVersion: integration/v1
kind: Step
name: create-annotation
version: 1
summary: Post an annotation to a Grafana dashboard

description: |
  Annotate a Grafana dashboard with an event.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/grafana-step-create-annotation

examples:
- summary: Post an annotation with a given message
  content:
    apiVersion: v1
    kind: Workflow
    parameters:
      text:
        description: The annotation message
        default: Production deployment
      dashboardId:
        description: The optional numeric identifier of the dashboard to update
      panelId:
        description: The optional numeric identifier of the panel to annotate
    steps:
    - name: annotate-dashboard
      image: relaysh/grafana-step-create-annotation
      spec:
        connection: ${connections.grafana.my-grafana-connection}
        text: ${parameters.text}
        dashboardId: ${parameters.dashboardId}
        panelId: ${parameters.panelId}
        tags: [deploy, prod]

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    properties:
      connection:
        type: object
        x-relay-connectionType: grafana
        description: Grafana connection data
        properties:
          apiURL:
            type: string
            description: The Grafana URL to connect to
          apiToken:
            type: string
            description: A Grafana API token
        required:
        - apiURL
        - apiToken
      dashboardId:
        type: integer
        description: The optional numeric identifier of the dashboard to update
      panelId:
        type: integer
        description: The optional numeric identifier of the dashboard panel to annotate
      tags:
        type: array
        items:
          type: string
        description: Optional tags to add to the annotation
      text:
        type: string
        description: The text of the annotation
      time:
        type: object
        properties:
          start:
            type: integer
            description: Start time as an epoch number with millisecond resolution
          end:
            type: integer
            description: End time as an epoch number with millisecond resolution
    required:
    - connection
    - text

outputs:
  $schema: http://json-schema.org/draft-07/schema#
  type: object
  properties:
    resultCode:
      type: integer
      description: The numeric HTTP code received from the Grafana API
    resultText:
      type: string
      description: The text message received from the Grafana API response
