FROM relaysh/core:latest-python
COPY "./step.py" "/entrypoint.py"
ENTRYPOINT []
CMD ["python3", "/entrypoint.py"]

LABEL "org.opencontainers.image.title"="Search Grafana Dashboards"
LABEL "org.opencontainers.image.description"="Allows searching for Grafana dashboards"
LABEL "com.puppet.nebula.sdk.version"="v1"
