FROM relaysh/core:latest-python
COPY "./step.py" "/entrypoint.py"
ENTRYPOINT []
CMD ["python3", "/entrypoint.py"]

LABEL "org.opencontainers.image.title"="Get data for a specific Grafana Dashboard"
LABEL "org.opencontainers.image.description"="This step retrieves data for a Grafana dashboard"
LABEL "com.puppet.nebula.sdk.version"="v1"
